export const products = [
    {
        id: 1,
        image: "assets/mini-console.jpeg",
        hoverImage: "assets/mini-console-hover.jpeg",
        name: "mini console",
        description:
            "Ideal for everyday shortcuts.  Adaptable to any workflow.",
        price: 0,
        isSoldOut: true,
        preOrder: true,
    },
    {
        id: 2,
        image: "assets/audio-console.jpeg",
        hoverImage: "assets/audio-console-hover.jpeg",
        name: "audio console",
        description: "Ideal for music & audio.  Adaptable to any workflow.",
        price: 0,
        isSoldOut: true,
        preOrder: true,
    },
    {
        id: 3,
        image: "assets/photo-console-box.jpeg",
        hoverImage: "assets/photo-console-item.jpeg",
        name: "photo console",
        description: "Ideal for photo & video.  Adaptable to any workflow.",
        price: 0,
        isSoldOut: true,
        preOrder: true,
    },
    {
        id: 4,
        image: "assets/video-console-box.jpeg",
        hoverImage: "assets/video-console.jpeg",
        name: "video console",
        description: "Ideal for video & film.  Adaptable to any workflow.",
        price: 0,
        isSoldOut: true,
        preOrder: true,
    },
    {
        id: 5,
        image: "assets/keyboard-multipad.jpg",
        hoverImage: "assets/keyboard-multipad-angle.jpeg",
        name: "monogram keyboard + multipad",
        description: "Adaptable to any workflow.",
        price: 0,
        isSoldOut: true,
        preOrder: true,
    },
    {
        id: 6,
        image: "assets/keyboard.jpg",
        hoverImage: "assets/keyboard-hover.jpeg",
        name: "monogram keyboard",
        price: 0,
        isSoldOut: true,
        preOrder: true,
    },
    {
        id: 7,
        image: "assets/multipad.png",
        hoverImage: "assets/multipad-angle.jpeg",
        name: "monogram multipad",
        price: 0,
        isSoldOut: true,
        preOrder: true,
    },
    {
        id: 8,
        image: "assets/core-box.jpeg",
        hoverImage: "assets/core.jpeg",
        name: "monogram core",
        price: "$159",
        isSoldOut: false,
        preOrder: true,
    },
    {
        id: 9,
        image: "assets/slider-module-box.jpeg",
        hoverImage: "assets/slider-module.jpeg",
        name: "slider module",
        price: 0,
        isSoldOut: true,
        preOrder: true,
    },
    {
        id: 10,
        image: "assets/orbiter-module-box.jpeg",
        hoverImage: "assets/orbiter-module.jpeg",
        name: "orbiter module",
        price: 0,
        isSoldOut: true,
        preOrder: true,
    },
    {
        id: 11,
        image: "assets/essential-keys-module-box.jpeg",
        hoverImage: "assets/essential-keys-module.jpeg",
        name: "essential keys module",
        price: 0,
        isSoldOut: true,
        preOrder: true,
    },
    {
        id: 12,
        image: "assets/dial-module-box.jpeg",
        hoverImage: "assets/dial-module-item.jpeg",
        name: "dial module",
        price: 0,
        isSoldOut: true,
        preOrder: true,
    },
    {
        id: 13,
        image: "assets/carrying-case-close.jpeg",
        hoverImage: "assets/carrying-case-open.jpeg",
        name: "monogram carrying case",
        price: 0,
        isSoldOut: true,
        preOrder: true,
    },
    {
        id: 14,
        image: "assets/console-pack-video.jpeg",
        hoverImage: "assets/console-pack-video.jpeg",
        name: "console pack: video",
        price: "$69",
        isSoldOut: false,
        preOrder: false,
    },
    {
        id: 15,
        image: "assets/console-pack-photo.jpeg",
        hoverImage: "assets/console-pack-photo.jpeg",
        name: "console pack: photo",
        price: "$39",
        isSoldOut: false,
        preOrder: false,
    },
    {
        id: 16,
        image: "assets/console-pack-audio.jpeg",
        hoverImage: "assets/console-pack-audio.jpeg",
        name: "console pack: audio",
        price: "$29",
        isSoldOut: false,
        preOrder: false,
    },
    {
        id: 17,
        image: "assets/console-care-yellow.jpeg",
        hoverImage: "assets/console-care-orange.jpeg",
        name: "monogram care",
        price: "$19 - $129",
        isSoldOut: false,
        preOrder: false,
    },
];
